# Generated by Django 3.1.3 on 2021-02-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKSTORE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Not verified'), (1, 'Verified'), (2, 'Owner found')], default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('picture', models.ImageField(blank=True, default='default.png', max_length=200, null=True, upload_to='pictures/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='add',
            name='bookname',
            field=models.CharField(max_length=200),
        ),
    ]
