# Generated by Django 3.1.3 on 2021-02-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKSTORE', '0002_auto_20210210_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditem',
            name='title',
        ),
        migrations.AddField(
            model_name='founditem',
            name='bookname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='founditem',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', max_length=200, null=True, upload_to='img'),
        ),
    ]
