# Generated by Django 3.1.3 on 2021-02-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKSTORE', '0003_auto_20210210_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add',
        ),
    ]
