# Generated by Django 3.1.3 on 2021-02-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKSTORE', '0004_delete_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoundItem',
            new_name='book',
        ),
    ]
