# Generated by Django 3.1.3 on 2021-02-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKSTORE', '0005_auto_20210211_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
