# Generated by Django 3.1.3 on 2021-02-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKSTORE', '0006_remove_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
    ]
